In [37]:
# Import modules
import pandas as pd
import numpy as np
import locale
# import matplotlib.pyplot as plt

# Set locale to use commas as thousands separator
locale.setlocale(locale.LC_ALL, '')
pd.options.display.max_rows = 15

In [38]:
# Import binary table
Y = pd.read_excel(r"D:\工作文件夹\妙盈\00. 消费碳足迹\EEIO model\妙盈EEIO\2020_update\raw data\binary_table.xlsx",sheet_name=0,index_col=0,header=0)
Y=Y.fillna(value=0)
Y

Crop cultivation  \
Agriculture,Forestry,Animal Husbandry and Fishery                1.0   
Mining and Washing of Coal                                       0.0   
Extraction of Petroleum and Natural Gas                          0.0   
Mining and Processing of Ferrous Metal Ores                      0.0   
Mining and Processing of Non-Ferrous Metal Ores                  0.0   
...                                                              ...   
Construction                                                     0.0   
Transport,Storage and Post                                       0.0   
Wholesale and Retail Trades,Hotels and Catering...               0.0   
Others                                                           0.0   
Residential                                                      0.0   

                                                    Forestry  \
Agriculture,Forestry,Animal Husbandry and Fishery        1.0   
Mining and Washing of Coal                               0.0   
Extraction of Petroleum and Natural Gas                  0.0   
Mining and Processing of Ferrous Metal Ores              0.0   
Mining and Processing of Non-Ferrous Metal Ores          0.0   
...                                                      ...   
Construction                                             0.0   
Transport,Storage and Post                               0.0   
Wholesale and Retail Trades,Hotels and Catering...       0.0   
Others                                                   0.0   
Residential                                              0.0   

                                                    Livestock and livestock products  \
Agriculture,Forestry,Animal Husbandry and Fishery                                1.0   
Mining and Washing of Coal                                                       0.0   
Extraction of Petroleum and Natural Gas                                          0.0   
Mining and Processing of Ferrous Metal Ores                                      0.0   
Mining and Processing of Non-Ferrous Metal Ores                                  0.0   
...                                                                              ...   
Construction                                                                     0.0   
Transport,Storage and Post                                                       0.0   
Wholesale and Retail Trades,Hotels and Catering...                               0.0   
Others                                                                           0.0   
Residential                                                                      0.0   

                                                    Fishery  \
Agriculture,Forestry,Animal Husbandry and Fishery       1.0   
Mining and Washing of Coal                              0.0   
Extraction of Petroleum and Natural Gas                 0.0   
Mining and Processing of Ferrous Metal Ores             0.0   
Mining and Processing of Non-Ferrous Metal Ores         0.0   
...                                                     ...   
Construction                                            0.0   
Transport,Storage and Post                              0.0   
Wholesale and Retail Trades,Hotels and Catering...      0.0   
Others                                                  0.0   
Residential                                             0.0   

                                                    Technical services for agriculture  \
Agriculture,Forestry,Animal Husbandry and Fishery                                  1.0   
Mining and Washing of Coal                                                         0.0   
Extraction of Petroleum and Natural Gas                                            0.0   
Mining and Processing of Ferrous Metal Ores                                        0.0   
Mining and Processing of Non-Ferrous Metal Ores                                    0.0   
...                                                             

In [39]:
list(Y.columns)

['Crop cultivation',
 'Forestry',
 'Livestock and livestock products',
 'Fishery',
 'Technical services for agriculture',
 'Coal mining and processing',
 'Crude petroleum and natural gas',
 'Ferrous metal ore mining',
 'Non-ferrous metal ore mining',
 'Non-metallic minerals mining',
 'Auxiliary mining services and other mining ',
 'Grain mill products',
 'Feeding stuff production',
 'Vegetable oil and forage',
 'Sugar refining',
 'Slaughtering and meat processing',
 'Prepared fish and seafood',
 'Other food processing',
 'Convenient foods',
 'Liquid milk and dairy products',
 'Spices and fermentation products',
 'Other food manufacturing',
 'Wines, spirits and liquors',
 'Non-alcoholic beverage',
 'Tea',
 'Tobacco products',
 'Cotton textiles',
 'Woolen textiles',
 'Hemp textiles ',
 'Knitted mills',
 'Finished textile products',
 'Wearing apparel',
 'Leather, furs, down and related products',
 'Footwear',
 'Sawmills, fibreboard, and products of wood, bamboo, cane, palm, straw, etc.',


In [40]:
# import 能源统计年鉴计算出的碳排放数据
Z = pd.read_excel(r"D:\工作文件夹\妙盈\00. 消费碳足迹\EEIO model\妙盈EEIO\2020_update\emissions\sector emissions\2020sector_emissions.xlsx",sheet_name=0,usecols=[0,1],index_col=[0],header=0)
Z=Z.iloc[0:46]
Z=Z.reindex(Y.index)
Z

emission
Agriculture,Forestry,Animal Husbandry and Fishery   1.010604e+08
Mining and Washing of Coal                          3.437752e+08
Extraction of Petroleum and Natural Gas             5.538292e+07
Mining and Processing of Ferrous Metal Ores         1.037480e+07
Mining and Processing of Non-Ferrous Metal Ores     2.571320e+06
...                                                          ...
Construction                                        4.607841e+07
Transport,Storage and Post                          7.094629e+08
Wholesale and Retail Trades,Hotels and Catering...  6.805693e+07
Others                                              1.662039e+08
Residential                                         3.770399e+08

[47 rows x 1 columns]

In [41]:
# 读入投入产出表

IOtable_2018 = pd.read_excel(r"D:\工作文件夹\妙盈\00. 消费碳足迹\EEIO model\妙盈EEIO\2018 results\2018投入产出表.xlsx",sheet_name="生产价投入产出表",skiprows=4,index_col=[0,1,2],header=[0,1])
IOtable_2020 = pd.read_excel(r"D:\工作文件夹\妙盈\00. 消费碳足迹\EEIO model\妙盈EEIO\2020_update\raw data\2020-竞争性投入产出表.xlsx",sheet_name=0,skiprows=4,index_col=[0,1,2],header=[0,1])

IOtable=[IOtable_2018,IOtable_2020]

In [42]:
level_1_index=IOtable[1].index.get_level_values(1)
level_1_index=level_1_index[0:153]
level_1_index

Index(['农产品', '林产品', '畜牧产品', '渔产品', '农、林、牧、渔服务产品', '煤炭开采和洗选产品', '石油和天然气开采产品',
       '黑色金属矿采选产品', '有色金属矿采选产品', '非金属矿采选产品',
       ...
       '教育', '卫生', '社会工作', '新闻和出版', '广播、电视、电影和影视录音制作', '文化艺术', '体育', '娱乐',
       '社会保障', '公共管理和社会组织'],
      dtype='object', length=153)

In [43]:
# 计算出最终需求矩阵的对角阵, 注：这里已经把进口IM列减去了

Y_=[i.iloc[:153,163]-i.iloc[:153,164] for i in IOtable]

Y_[1]

中间投入  农产品          01001    1.412066e+08
      林产品          02002   -3.773667e+06
      畜牧产品         03003    1.614158e+08
      渔产品          04004    5.834024e+07
      农、林、牧、渔服务产品  05005    1.963963e+07
                                ...     
      文化艺术         88145    2.480911e+07
      体育           89146    1.572686e+07
      娱乐           90147    2.126916e+07
      社会保障         94148    1.119233e+07
      公共管理和社会组织    91149    7.505246e+08
Length: 153, dtype: float64

In [44]:
Y_diag=[np.diag(i) for i in Y_]
Y_diag[0]

array([[ 1.07639239e+08,  0.00000000e+00,  0.00000000e+00, ...,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
       [ 0.00000000e+00, -5.12503911e+06,  0.00000000e+00, ...,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
       [ 0.00000000e+00,  0.00000000e+00,  1.09171993e+08, ...,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
       ...,
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00, ...,
         2.84956144e+07,  0.00000000e+00,  0.00000000e+00],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00, ...,
         0.00000000e+00,  9.71549887e+06,  0.00000000e+00],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00, ...,
         0.00000000e+00,  0.00000000e+00,  6.95567404e+08]])

In [45]:
# 计算出居民消费支出（156行）、资本形成总额（161行）、政府消费支出（157行）等分项

# Y_hh = IOtable.iloc[:153,156].to_numpy()
# Y_gov = IOtable.iloc[:153,157].to_numpy()
# Y_cap = IOtable.iloc[:153,161].to_numpy()
# Y_ex=IOtable.iloc[:153,162].to_numpy()


In [46]:
# 最终产出矩阵X，变成一维numpy数组
X=[i.iloc[:153,165].to_numpy() for i in IOtable]
X

[array([6.01622460e+08, 5.53410739e+07, 2.75267010e+08, 1.21784637e+08,
        5.86540000e+07, 2.36261314e+08, 1.29419240e+08, 5.85251285e+07,
        5.20520099e+07, 7.79071111e+07, 1.81735406e+07, 1.28627593e+08,
        8.43479773e+07, 8.45140980e+07, 1.28913589e+07, 1.59892113e+08,
        6.20950084e+07, 1.10659762e+08, 2.75456950e+07, 4.66902559e+07,
        3.08761442e+07, 1.37088894e+08, 8.88877008e+07, 6.85248644e+07,
        2.50815398e+07, 9.13393532e+07, 2.52570753e+08, 2.48534703e+07,
        2.26274521e+07, 3.53784800e+07, 5.29644095e+07, 2.29656803e+08,
        7.77251534e+07, 7.57092589e+07, 1.65305600e+08, 1.01814120e+08,
        1.86830032e+08, 8.28726327e+07, 4.26520596e+07, 9.99361389e+07,
        3.86862247e+08, 6.32015333e+07, 2.57802755e+08, 6.74848902e+07,
        2.63760066e+07, 6.81016956e+07, 1.91193692e+08, 1.96842729e+08,
        4.00714686e+07, 2.79532770e+08, 8.14517664e+07, 7.96418199e+07,
        2.67383130e+08, 1.39371616e+08, 1.96839244e+08, 1.356325

In [47]:
# 求出需求系数矩阵A
A=[(i.iloc[:153,:153]/i.iloc[159,0:153]).to_numpy() for i in IOtable]
A[0],A[1]

(array([[9.91385173e-02, 0.00000000e+00, 8.08355799e-02, ...,
         4.87111907e-04, 0.00000000e+00, 0.00000000e+00],
        [2.09729111e-07, 5.63757627e-02, 0.00000000e+00, ...,
         1.64797297e-04, 0.00000000e+00, 0.00000000e+00],
        [1.55816912e-07, 0.00000000e+00, 6.94063728e-02, ...,
         1.86114685e-03, 0.00000000e+00, 0.00000000e+00],
        ...,
        [2.03395674e-06, 6.17522850e-05, 2.80453746e-06, ...,
         2.98590410e-02, 2.75719247e-04, 8.65969022e-04],
        [1.85467644e-06, 1.59868949e-04, 1.90490947e-05, ...,
         5.62582050e-05, 9.06547513e-03, 1.73501630e-04],
        [1.86368525e-04, 1.83549972e-03, 4.16993122e-04, ...,
         3.26549118e-04, 1.81479408e-04, 2.41268947e-02]]),
 array([[1.15355578e-01, 0.00000000e+00, 7.92348457e-02, ...,
         6.07523396e-04, 0.00000000e+00, 0.00000000e+00],
        [2.02105241e-07, 5.86381544e-02, 0.00000000e+00, ...,
         1.83238901e-04, 0.00000000e+00, 0.00000000e+00],
        [2.10828188e-07, 

In [48]:
n=153
I=np.identity(n)
I

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [49]:
L=[np.linalg.inv(I-i) for i in A]
L[1]

array([[1.14287067e+00, 2.95522146e-02, 2.44829068e-01, ...,
        5.73925496e-02, 1.14819937e-02, 1.93905605e-02],
       [9.86854911e-04, 1.06378890e+00, 6.40162529e-04, ...,
        1.95305467e-03, 1.04732764e-03, 2.91693140e-03],
       [1.71919969e-03, 5.82785467e-03, 1.07017816e+00, ...,
        1.12960504e-02, 3.11525816e-03, 4.92959708e-03],
       ...,
       [6.97942738e-04, 8.92120827e-04, 6.39655442e-04, ...,
        1.03441278e+00, 1.33215040e-03, 2.46528651e-03],
       [7.82104566e-05, 2.39312260e-04, 7.18470099e-05, ...,
        1.60365754e-04, 1.00883685e+00, 2.72860467e-04],
       [4.31689957e-04, 2.24205908e-03, 5.59468764e-04, ...,
        8.56970964e-04, 4.15763468e-04, 1.02769928e+00]])

In [50]:
# 求出直接碳强度f,转换成对角阵
# f=IO_emissions_series/X
f_new_2018=pd.read_excel(r"D:\工作文件夹\妙盈\03. 酒店\map_project\total_emissions_factors_2018.xlsx")
f_new_2020=pd.read_excel(r"D:\工作文件夹\妙盈\03. 酒店\map_project\total_emissions_factors_2020.xlsx")
f_new=[f_new_2018["总排放因子"],f_new_2018["CO2排放因子"],f_new_2020["总排放因子"],f_new_2020["CO2排放因子"]]
f_new[3]

0      0.065769
1      0.079681
2      0.045562
3      0.122336
4      0.364566
         ...   
148    0.016994
149    0.028354
150    0.004735
151    0.005161
152    0.020117
Name: CO2排放因子, Length: 153, dtype: float64

In [51]:
# f_diag有4个elements
f_diag=[np.diag(i.to_numpy()) for i in f_new]  #对角阵的列表
f_diag[3]

array([[0.06576905, 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.07968104, 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.0455617 , ..., 0.        , 0.        ,
        0.        ],
       ...,
       [0.        , 0.        , 0.        , ..., 0.00473485, 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.00516065,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.02011678]])

In [52]:
# 求出总排放因子,"整数除法//"
Total_factors=[f_diag[i] @ L[i // 2] for i in range(len(f_diag))]
# 消费碳排放因子=pd.DataFrame(Total_factors,index=level_1_index,columns=level_1_index)
# 消费碳排放因子=消费碳排放因子.sum(axis=0)
#消费碳排放因子.to_excel("消费碳排放因子_new.xlsx")
# np.shape(Total_factors[3])
Total_factors[3]

array([[7.51655213e-02, 1.94362116e-03, 1.61021759e-02, ...,
        3.77465362e-03, 7.55159851e-04, 1.27529879e-03],
       [7.86336287e-05, 8.47638089e-02, 5.10088180e-05, ...,
        1.55621433e-04, 8.34521590e-05, 2.32424136e-04],
       [7.83296542e-05, 2.65526945e-04, 4.87591325e-02, ...,
        5.14667217e-04, 1.41936446e-04, 2.24600805e-04],
       ...,
       [3.30465455e-06, 4.22405878e-06, 3.02867291e-06, ...,
        4.89778989e-03, 6.30753304e-06, 1.16727631e-05],
       [4.03616934e-07, 1.23500725e-06, 3.70777402e-07, ...,
        8.27591817e-07, 5.20625570e-03, 1.40813786e-06],
       [8.68421262e-06, 4.51030129e-05, 1.12547110e-05, ...,
        1.72394978e-05, 8.36382291e-06, 2.06740021e-02]])

In [53]:
Total_factors=[pd.DataFrame(i,index=level_1_index,columns=level_1_index) for i in Total_factors]
Total_factors[3]

农产品       林产品          畜牧产品           渔产品   农、林、牧、渔服务产品  \
农产品          7.516552e-02  0.001944  1.610218e-02  9.261545e-03  1.256568e-02   
林产品          7.863363e-05  0.084764  5.100882e-05  9.104464e-05  4.687354e-04   
畜牧产品         7.832965e-05  0.000266  4.875913e-02  1.813388e-04  1.696131e-03   
渔产品          1.313858e-04  0.000412  1.734961e-03  1.277297e-01  2.340230e-03   
农、林、牧、渔服务产品  9.635031e-03  0.049212  3.305571e-03  1.468312e-02  3.987719e-01   
...                   ...       ...           ...           ...           ...   
文化艺术         1.691372e-06  0.000005  1.291800e-06  4.408598e-06  5.124807e-06   
体育           0.000000e+00  0.000000  0.000000e+00  0.000000e+00  0.000000e+00   
娱乐           3.304655e-06  0.000004  3.028673e-06  4.528725e-06  5.130754e-06   
社会保障         4.036169e-07  0.000001  3.707774e-07  4.639495e-07  6.595795e-07   
公共管理和社会组织    8.684213e-06  0.000045  1.125471e-05  1.545873e-05  1.397945e-05   

             煤炭开采和洗选产品  石油和天然气开采产品  黑色金属矿采选产品  有色金属矿采选产品  非金属矿采选产品  ...  \
农产品           0.000676    0.000528   0.000535   0.000794  0.000864  ...   
林产品           0.000551    0.000159   0.000204   0.000275  0.000238  ...   
畜牧产品          0.000100    0.000087   0.000076   0.000120  0.000132  ...   
渔产品           0.000173    0.000102   0.000143   0.000182  0.000182  ...   
农、林、牧、渔服务产品   0.000660    0.000316   0.000317   0.000439  0.000441  ...   
...                ...         ...        ...        ...       ...  ...   
文化艺术          0.000004    0.000007   0.000004   0.000003  0.000004  ...   
体育            0.000000    0.000000   0.000000   0.000000  0.000000  ...   
娱乐            0.000010    0.000007   0.000009   0.000008  0.000007  ...   
社会保障          0.000002    0.000002   0.000001   0.000002  0.000002  ...   
公共管理和社会组织     0.000010    0.000006   0.000009   0.000011  0.000012  ...   

                       教育            卫生      社会工作     新闻和出版  广播、电视、电影和影视录音制作  \
农产品          1.551689e-03  4.578925e-03  0.005112  0.002680         0.002263   
林产品          1.502682e-04  1.544016e-04  0.000123  0.000922         0.000198   
畜牧产品         1.558934e-04  1.665301e-03  0.000274  0.000240         0.000443   
渔产品          3.946259e-04  3.622198e-04  0.000288  0.000520         0.000974   
农、林、牧、渔服务产品  4.989632e-04  1.579874e-03  0.000880  0.001304         0.001758   
...                   ...           ...       ...       ...              ...   
文化艺术         5.479028e-06  2.687015e-06  0.000004  0.000005         0.000014   
体育           0.000000e+00  0.000000e+00  0.000000  0.000000         0.000000   
娱乐           6.802274e-06  8.455899e-06  0.000013  0.000012         0.000012   
社会保障         5.503594e-07  8.215794e-07  0.000004  0.000007         0.000001   
公共管理和社会组织    4.101708e-05  1.776514e-05  0.000024  0.000018         0.000022   

                 文化艺术        体育            娱乐      社会保障  公共管理和社会组织  
农产品          0.002279  0.001770  3.774654e-03  0.000755   0.001275  
林产品          0.000332  0.000210  1.556214e-04  0.000083   0.000232  
畜牧产品         0.000279  0.000266  5.146672e-04  0.000142   0.000225  
渔产品          0.000342  0.000570  5.444677e-04  0.000443   0.000419  
农、林、牧、渔服务产品  0.001636  0.000870  8.784770e-04  0.000277   0.000889  
...               ...       ...           ...       ...        ...  
文化艺术         0.018935  0.000002  2.398122e-06  0.000002   0.000024  
体育           0.000000  0.031394  0.000000e+00  0.000000   0.000000  
娱乐           0.000053  0.000049  4.897790e-03  0.000006   0.000012  
社会保障         0.000002  0.000001  8.275918e-07  0.005206   0.000001  
公共管理和社会组织    0.000055  0.000034  1.723950e-05  0.000008   0.020674  

[153 rows x 153 columns]

In [54]:
# 求出scope1排放因子，是行向求和还是列向求和？
factor1=[i@I.sum(axis=0) for i in f_diag]
factor1[1]

array([6.57690527e-02, 7.96810431e-02, 4.55616964e-02, 1.22335526e-01,
       3.64565700e-01, 2.30318629e-01, 3.34444015e-01, 1.74058793e-01,
       4.56850049e-02, 1.22926020e-01, 2.81459460e-01, 3.63046722e-02,
       4.28812118e-02, 3.72149839e-02, 1.12759543e-01, 2.56170110e-02,
       4.57453411e-02, 8.75117019e-02, 6.20258791e-02, 4.65236252e-02,
       1.12555725e-01, 6.08914189e-02, 6.28040915e-02, 7.85475911e-02,
       2.85952714e-02, 5.56412247e-03, 5.47491559e-02, 7.34912452e-02,
       1.03259904e-01, 1.27573838e-02, 1.19602328e-02, 6.65630316e-03,
       6.86574896e-03, 7.80763553e-03, 1.18241858e-02, 6.93744544e-03,
       1.04971111e-01, 2.76844781e-02, 2.96011668e-02, 2.29825940e-02,
       1.29217491e+00, 8.22025822e-01, 1.34652231e+00, 8.11392883e-01,
       4.53239882e-01, 3.03804996e-01, 9.95300831e-01, 5.51258240e-01,
       4.85347506e-02, 4.50599013e-02, 1.31570843e-01, 2.45211469e-02,
       3.00033947e-02, 1.95933757e+00, 5.42345608e-01, 3.21259266e+00,
      

In [55]:
# 求出scope2排放因子,即电力行业单独摘出
factor2=[(f_diag[i]@A[i//2]) for i in range(len(f_diag))]
factor2=[i[99,:] for i in factor2]
factor2[3]

array([6.86405194e-02, 1.41514799e-02, 5.42005068e-03, 2.94034967e-02,
       5.46023405e-02, 2.00558392e-01, 1.97342758e-01, 3.45630721e-01,
       4.81063854e-01, 4.34607445e-01, 1.31968438e-01, 3.84367987e-02,
       5.39829791e-02, 2.88219922e-02, 1.06132389e-01, 1.46442134e-02,
       1.44738289e-02, 5.81087434e-02, 3.97252706e-02, 2.49522328e-02,
       7.37406531e-02, 4.84977919e-02, 2.45121782e-02, 6.66377329e-02,
       3.39813721e-02, 1.66677954e-02, 1.11093916e-01, 3.51024776e-02,
       9.45714609e-02, 1.02993972e-01, 4.51140337e-02, 5.11326115e-02,
       1.04046914e-02, 5.47618102e-02, 1.33302024e-01, 6.92527603e-02,
       1.65920271e-01, 3.39380833e-02, 5.64079014e-02, 5.44387933e-02,
       1.15552141e-01, 1.53533987e-01, 6.34709495e-01, 3.07640621e-01,
       1.17805747e-01, 6.19552979e-02, 1.22018944e-01, 1.16580874e-01,
       4.63128422e-02, 8.31296746e-02, 1.93541886e-01, 8.08255053e-02,
       1.05606964e-01, 5.15115506e-01, 1.78631104e-01, 2.73974145e-01,
      

In [56]:
factor3=[Total_factors[i].sum(axis=0)-factor1[i]-factor2[i] for i in range(len(f_diag))]
factor3[0]

农产品            0.713029
林产品            0.494931
畜牧产品           0.623267
渔产品            0.481586
农、林、牧、渔服务产品    0.714874
                 ...   
文化艺术           0.446614
体育             0.487138
娱乐             0.412268
社会保障           0.181509
公共管理和社会组织      0.428227
Length: 153, dtype: float64

In [57]:
#创建3个scope排放因子dataframe

# 将 ndarray 组成字典
data = [{'范围1排放因子': factor1[i], '范围2排放因子': factor2[i], '范围3排放因子': factor3[i]} for i in range(0,4)]
data[0]


{'范围1排放因子': array([6.76833162e-01, 7.99897532e-02, 1.15791281e+00, 1.22809494e-01,
        3.65978145e-01, 3.20099502e+00, 5.94337567e-01, 1.74661883e-01,
        4.58670594e-02, 1.23445698e-01, 2.82337294e-01, 3.64429299e-02,
        4.30445147e-02, 3.73567082e-02, 1.13188961e-01, 2.57145672e-02,
        4.59195513e-02, 8.78449694e-02, 6.22674303e-02, 4.67048050e-02,
        1.12994058e-01, 6.11285521e-02, 6.30472605e-02, 7.88517168e-02,
        2.87059884e-02, 5.57857920e-03, 5.49539069e-02, 7.37660879e-02,
        1.03646076e-01, 1.28041371e-02, 1.20040647e-02, 6.68069721e-03,
        6.89356160e-03, 7.83926368e-03, 1.18618855e-02, 6.95412668e-03,
        1.05419083e-01, 2.77706289e-02, 2.96945314e-02, 2.30550831e-02,
        1.29416149e+00, 8.47755575e-01, 1.35051916e+00, 8.13801326e-01,
        4.54585226e-01, 3.04706775e-01, 9.98255164e-01, 5.52894530e-01,
        4.86788154e-02, 4.52452785e-02, 1.32146498e-01, 2.46106592e-02,
        3.01129195e-02, 1.96216737e+00, 5.43128897e-0

In [58]:
# 创建 DataFrame 并设置索引
df123 = [pd.DataFrame(data[i], index=level_1_index) for i in range(0,4)]
# df123=df123.loc[colls,:]
df123[3]

范围1排放因子   范围2排放因子   范围3排放因子
农产品          0.065769  0.068641  0.529194
林产品          0.079681  0.014151  0.411133
畜牧产品         0.045562  0.005420  0.290494
渔产品          0.122336  0.029403  0.348896
农、林、牧、渔服务产品  0.364566  0.054602  0.483557
...               ...       ...       ...
文化艺术         0.016994  0.021517  0.376473
体育           0.028354  0.073976  0.393701
娱乐           0.004735  0.077283  0.334714
社会保障         0.005161  0.027334  0.143262
公共管理和社会组织    0.020117  0.050842  0.359629

[153 rows x 3 columns]

In [59]:
#格式化结果输出
for i,df in enumerate(df123):
    if i==0 or i==2:
        year = 2018
        filename=f"D:\\工作文件夹\\妙盈\\03. 酒店\\map_project\\{year+i}年范围1-3因子.xlsx"
        df.to_excel(filename)
    elif i==1 or i==3:
        year = 2017
        filename=f"D:\\工作文件夹\\妙盈\\03. 酒店\\map_project\\{year+i}年CO2范围1-3因子.xlsx"
        df.to_excel(filename)


In [60]:
for i,df in enumerate([df123[2],df123[3]]):
    year = 2020
    filename=f"D:\\工作文件夹\\妙盈\\03. 酒店\\map_project\\{year}年CO2范围1-3因子.xlsx"
    df.to_excel(filename)